default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: caten_church_dev
  host: localhost # add this line will use tcp instead of unix socket
  username: postgres
  password: postgres

test:
  <<: *default
  database: caten_church_test
  host: localhost # add this line will use tcp instead of unix socket
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV.key('DATABASE_URL') || Rails.application.credentials[:production][:database_url] %>
