default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: caten_church_dev
  username: caten_church
  password: caten_church

test:
  <<: *default
  database: caten_church_test
  username: caten_church
  password: caten_church

production:
  <<: *default
  url: <%= ENV.key('DATABASE_URL') || Rails.application.credentials[:production][:database_url] %>
